create table
  public.potions (
    potion_id integer generated by default as identity,
    potion_name character varying not null,
    quantity integer null,
    price integer null,
    red_ml integer null,
    blue_ml integer null default 0,
    green_ml integer null default 0,
    constraint potions_table_pkey primary key (potion_id)
  ) tablespace pg_default;


  create table
  public.global_inventory (
    num_green_potions integer generated by default as identity,
    num_green_ml integer not null,
    gold integer not null,
    num_red_potions integer null,
    num_red_ml integer null,
    num_blue_potions integer null,
    num_blue_ml integer null,
    id integer generated by default as identity,
    constraint global_inventory_pkey primary key (id),
    constraint global_inventory_id_key unique (id)
  ) tablespace pg_default;

  create table
  public.carts (
    cart_id integer generated by default as identity,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_item_id integer not null,
    cart_id integer null,
    potion_id integer null,
    quantity integer null,
    constraint cart_items_pkey primary key (cart_item_id),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint public_cart_items_potion_id_fkey foreign key (potion_id) references potions (potion_id)
  ) tablespace pg_default;